export const MAX_ATP_PLAYERS = 150;

export const ATP_SOURCE = "AGE202";

export const COUNTRY_CODES: Record<string, string> = {
  Argentina: "ARG",
  Australia: "AUS",
  Austria: "AUT",
  Belgium: "BEL",
  Brazil: "BRA",
  Bulgaria: "BUL",
  Canada: "CAN",
  Chile: "CHI",
  China: "CHN",
  Croatia: "CRO",
  Czechia: "CZE",
  "Czech Republic": "CZE",
  Denmark: "DEN",
  Finland: "FIN",
  France: "FRA",
  Germany: "GER",
  Greece: "GRE",
  Hungary: "HUN",
  Italy: "ITA",
  Japan: "JPN",
  Netherlands: "NED",
  Norway: "NOR",
  Poland: "POL",
  Portugal: "POR",
  Romania: "ROU",
  Serbia: "SRB",
  Slovakia: "SVK",
  Slovenia: "SLO",
  Spain: "ESP",
  Sweden: "SWE",
  Switzerland: "SUI",
  Tunisia: "TUN",
  Ukraine: "UKR",
  "United Kingdom": "GBR",
  "Great Britain": "GBR",
  "United States": "USA",
  USA: "USA",
};